repos:
  # generic hooks (in accordance with https://opencorporates.atlassian.net/wiki/x/dgAFAg)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    - id: no-commit-to-branch
      args: [--branch, master]
    - id: trailing-whitespace
    - id: end-of-file-fixer

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
    - id: conventional-pre-commit
      stages: [commit-msg]

  # iac hooks (in accordance with https://opencorporates.atlassian.net/wiki/x/dgAFAg)
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.469
    hooks:
      - id: checkov

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: terraform-fmt

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10
        args: [--line-length=88]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        language_version: python3.10
#
#  - repo: https://github.com/pre-commit/mirrors-mypy
#    rev: v1.5.1
#    hooks:
#      - id: mypy
#        language_version: python3.10

  - repo: local
    hooks:
      - id: docstring-check
        name: Check docstrings
        entry: poetry run ruff check --select D
        language: system
        types: [python]
        pass_filenames: false

      - id: class-naming-check
        name: Check class naming conventions
        entry: poetry run python scripts/check_class_naming.py
        language: system
        types: [python]
        pass_filenames: false

#      - id: unit-tests
#        name: Run unit tests only
#        entry: poetry run pytest tests/unit/ -v --tb=short
#        language: system
#        types: [python]
#        pass_filenames: false
#        stages: [commit]
