repos:
  # generic hooks (in accordance with https://opencorporates.atlassian.net/wiki/x/dgAFAg)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: no-commit-to-branch
        args: [--branch, master]
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]

  # iac hooks (in accordance with https://opencorporates.atlassian.net/wiki/x/dgAFAg)
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.469
    hooks:
      - id: checkov

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: terraform-fmt

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.100.0
    hooks:
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true

  # python hooks (in accordance with https://opencorporates.atlassian.net/wiki/x/BQB9DQ)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.12
    hooks:
      # Run the linter (uses ruff config in pyproject.toml, see [tool.ruff.lint] section)
      - id: ruff-check
        args: [--fix]
      # Run the formatter (uses ruff config in pyproject.toml, see [tool.ruff.format] section)
      - id: ruff-format
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.1
    hooks:
      # Run the type checker (using mypy config in pyproject.toml, see [tool.mypy] section)
      - id: mypy
