repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: no-commit-to-branch
    args: [--branch, master]
  - id: trailing-whitespace
  - id: end-of-file-fixer

- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.2.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]

- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.30
  hooks:
  - id: terraform-fmt

- repo: https://github.com/bridgecrewio/checkov.git
  rev: 3.2.464
  hooks:
  - id: checkov

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.100.0
  hooks:
  - id: terraform_docs
    args:
      - --hook-config=--path-to-file=README.md
      - --hook-config=--add-to-existing-file=true
