site_name: Data Pipeline - Fetcher Application Documentation
site_description: A composable, streaming-first fetch framework for Python
site_author: OpenCorporates
site_url: https://openc.github.io/data-fetcher-sftp

# Repository
repo_name: openc/data-fetcher-sftp
repo_url: https://github.com/openc/data-fetcher-sftp
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  logo: assets/OC_Fetcher_Logo_New.svg
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github

# Plugins
plugins:
  - search:
      lang: en
  - offline
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: 90%
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
  - mermaid2:
      arguments:
        theme: default
        themeVariables:
          primaryColor: '#9f1f34'
          primaryTextColor: '#2c3e50'
          primaryBorderColor: '#9f1f34'
          lineColor: '#6c757d'
          secondaryColor: '#f8f9fa'
          tertiaryColor: '#ffffff'

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - toc:
      permalink: true

# Navigation structure - User Guide and Contributing organization
nav:
  - Home: index.md

  - Architecture:
    - Architecture Documentation: architecture/README.md
    - Architecture Overview: architecture/overview/README.md
    - Orchestration: architecture/orchestration/README.md
    - Persistent Queue: architecture/queue/README.md
    - ProtocolConfig: architecture/protocol_config/README.md
    - Recipes: architecture/recipes/README.md
    - Locators: architecture/locators/README.md
    - Loaders: architecture/loaders/README.md
    - Storage: architecture/storage/README.md
    - Notifications: architecture/notifications/README.md
    - State Management: architecture/state_management/README.md
    - Retry Engine: architecture/retry_engine/README.md

  - User Guide:
    - User Guide Documentation: user_guide/README.md
    - Getting Started: user_guide/getting_started.md
    - Command Line Usage: user_guide/command_line_usage.md
    - Docker Usage: user_guide/docker_usage.md
    - Application Configuration: user_guide/application_configuration.md
    - Deployment: deployment/overview.md
    - Health Checks: deployment/health_checks.md

  - Recipes:
    - Recipes Documentation: configurations/README.md
    - Contributing:
      - Creating a Recipe: configurations/creating_a_recipe.md
    - Available Strategies:
      - API:
        - FR - Siren:
          - TrackingApiLoader: configurations/strategies/api/siren/tracking_api_loader.md
          - ComplexPaginationBundleLocator: configurations/strategies/api/siren/complex_pagination_bundle_locator.md
          - ReversePaginationBundleLocator: configurations/strategies/api/siren/reverse_pagination_bundle_locator.md
          - SingleApiBundleLocator: configurations/strategies/api/siren/single_api_bundle_locator.md
      - SFTP:
        - Loaders:
          - SFTPLoader: configurations/strategies/sftp/loaders/sftp_loader.md
        - Locators:
          - DirectorySftpBundleLocator: configurations/strategies/sftp/locators/generic_directory_bundle_locator.md
          - FileSftpBundleLocator: configurations/strategies/sftp/locators/generic_file_bundle_locator.md
    - Available Recipes:
      - FR - France API: configurations/fr_api.md
      - US_FL - US Florida SFTP: configurations/us_fl_sftp.md

  - Contributing:
    - Contributing Guide: contributing/contributing_guide.md
    - Development Setup: contributing/development_setup.md
    - Code Standards: contributing/code_standards.md
    - Logging Development: contributing/logging_development.md
    - Testing:
      - Testing Guide: testing/overview.md
      - Test Cases Framework: testing/test_cases_framework.md
      - Writing Tests: testing/writing_tests.md
      - Mock Services: testing/mock_services.md
      - Debugging Tests: testing/debugging_tests.md
      - Mock Environments:
        - Mock Environments Documentation: testing/mock_environments/README.md
        - FR Test Setup: testing/mock_environments/fr_test_setup.md
        - US FL Test Setup: testing/mock_environments/us_fl_test_setup.md

  - Troubleshooting: troubleshooting/troubleshooting_guide.md

  - References:
    - References Documentation: references/README.md
    - Architecture Decision Records:
      - ADR Documentation: adr/README.md
      - "ADR 0001: Record Architecture Decisions": adr/0001-record-architecture-decisions.md
      - "ADR 0003: Checkov Exclusion List": adr/0003-checkov-exclusion-list.md
    - Additional Resources:
      - Terminology: references/terminology.md
      - Factory Functions: references/factory_functions.md
      - Naming Conventions: references/naming_conventions.md
      - Retry Consolidation Summary: references/retry_consolidation_summary.md
      - US Florida Test Setup: references/us_fl_test_setup.md
      - Diagrams: references/diagrams/README.md

# Extra configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/openc/data-fetcher-sftp
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/data-fetcher-sftp/

# Custom CSS for OpenCorporates branding
extra_css:
  - stylesheets/opencorporates.css
  - stylesheets/logo-sizing.css

# Custom JavaScript for enhanced functionality
extra_javascript:
  - assets/javascripts/mermaid-to-lightbox.js

# Copyright
copyright: Copyright &copy; 2025 OpenCorporates
