version: '3.8'

services:
  # SFTP server for US FL testing
  sftp-server:
    image: atmoz/sftp:alpine
    ports:
      - "${SFTP_PORT:-2222}:22"
    volumes:
      - ./data:/home/test/data
    command: test:test:1001:1001:data
    environment:
      - SFTP_USERS=test:test:1001:1001:data
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "22" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - us_fl_network

  # LocalStack for S3 and AWS services testing
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    environment:
      - SERVICES=s3,secretsmanager
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - us_fl_network

networks:
  us_fl_network:
    driver: bridge
