version: '3.8'

services:
  # Mock SIREN API server for French configuration
  siren-api:
    build:
      context: ../../images/api_fr_siren
      dockerfile: Dockerfile
    ports:
      - "${SIREN_API_PORT:-5001}:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5000/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fr_network

  # LocalStack for S3 and AWS services testing
  localstack:
    image: localstack/localstack:3.0
    ports:
      - "${LOCALSTACK_PORT:-4566}:4566"
    environment:
      - SERVICES=s3,secretsmanager
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:4566/_localstack/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - fr_network

networks:
  fr_network:
    driver: bridge
