us_florida:
  # SFTP Florida Path
  remote_dir: "/Public/doc/cor" # Parent directory
  filename_pattern: "[YYYYMMDD]c.txt"

  # S3 Configuration
  s3_bucket: "oc-[env]-data-orchestration-fetcher-raw" # Your S3 bucket
  s3_prefix: "us_florida/doc/cor" # S3 output path

  # AWS Configuration
  secret_name: "us_florida"
  region_name: "eu-west-2"

  # Metadata
  meta_source_system: "FloridaDOE_SFTP"
  meta_source_entity: "company"
  meta_load_name: "data-fetcher-sftp"
  meta_load_version: "1.0.0"

  # Scheduling
  schedule_interval: "0 5 * * *" # Run daily at 5 AM UTC
  schedule_start_date: "2025-01-01" # Start date for DAG
  schedule_catchup: True # Catch up if any runs were missed
  schedule_max_active_runs: 10 # Only one run at a time
