name: python

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

on:
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  call-python:
    uses: openc/gh-actions/.github/workflows/reusable-python.yaml@bot-migration-python
    with:
      python-version: "3.13"

      # ruff inputs
      enable-ruff: true
      ruff-version: "0.12.11"
      ruff-select-rules: "E,F,I,B,SIM,S"

      # mypy inputs
      enable-mypy: true
      mypy-version: "1.17.1"
